4
0 1 The solution converged. 14.134740352630615
1.0 1 The solution converged. -2.765655517578125e-05
Traceback (most recent call last):
  File "/home/tm7623/vortex_pair/solver.py", line 254, in <module>
    save(file, A, K, N, NU, NV, ier, EE, ME, HE, V, Fu, Fv, C, EED, MED, HED)
  File "/home/tm7623/vortex_pair/files.py", line 9, in save
    arr[9:] = np.concatenate((V.flatten(), Fu.flatten(), Fv.flatten(), C.flatten(), electric_energy_density.flatten(), magnetic_energy_density.flatten(), hydraulic_energy_density.flatten()))
    ~~~^^^^
ValueError: could not broadcast input array from shape (2800,) into shape (2801,)
Traceback (most recent call last):
  File "/home/tm7623/vortex_pair/plotter.py", line 12, in <module>
    A, K, N, NU, NV, ier, _, _, _, V, Fu, Fv, C, EED, MED, HED = load(file)
                                                                 ^^^^^^^^^^
  File "/home/tm7623/vortex_pair/files.py", line 13, in load
    arr = np.load(file)
          ^^^^^^^^^^^^^
  File "/usr/licensed/anaconda3/2023.9/lib/python3.11/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/4.npy'
